### DISCUSSION TITLE
Help to configure Switch AAI authentification

### DISCUSSION THREAD

**Discussion by jejmule** [leihs/leihs#1318] [Q&A / Community Support] [answered]
I am configuring leihs at UNIL, I have a fresh leihs installed on ubuntu server.
I have followed the instructions to deploy https://github.com/functional-swiss/leihs-switchaai-shibboleth-auth on my server

The deployment failed because the following variable is not defined : 
fatal: [issul.unil.ch]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'aai_auth_external_base_url' is undefined"}

Can you explain what change should be done to have the Switch AAI authentification installed? 

Thank you

**Comment by eins78** [comment, marked as answer]
Hi, first of all you should use a separate host, as the README states.
If your Leihs URL ist `leihs.example.org` it could be called `leihs-aai-auth.example.org`.
In this case, you'd need to create a vars file for that new host and fill it out, e.g.:

```yaml
# host_vars/leihs-aai-auth.example.org.yml
aai_auth_private_key: '{{example_aai_auth_private_key}}'
aai_auth_public_key: '{{example_aai_auth_public_key}}'
aai_auth_leihs_public_key: '{{example_aai_auth_leihs_public_key}}'
aai_auth_external_base_url:  https://leihs-aai-auth.example.org
ssl_certificate_file: /etc/letsencrypt/live/leihs-aai-auth.example.org/fullchain.pem
ssl_certificate_key_file: /etc/letsencrypt/live/leihs-aai-auth.example.org/privkey.pem
```
