### ISSUE TITLE
mail config needs "authentication type"

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#757]
In order for the `legacy` service to send emails using SMTP servers that do not use the (`ActionMailer`) default config of `authentication: 'plain'`, a new field needs to be added to `settings`.
Note that the new mail service does not have this problems (it seems to do the *right thing*™ and negotiates it using the SMTP protocoll)

```yaml
column: smtp_auth_type 
default: 'plain'
non-null: true
```
